[package]
name = "tetanus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5.7"
flate2 = "1.0.13"
itertools = "0.10.5"
fxhash = "0.2.1"
